import sys
import pandas as pd
df=pd.read_csv(r"D:\bscitE2_14\ds\student_info.csv")
print(df)
print(df.head(5))
print(df.tail(5))
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info)
print(df.describe)
print(df[['Name','Marks']])
print(df[df['Marks']>80])
print(df[df['City']=="Rajkot"])
print(df.sort_values(by='Marks',ascending=False))
print(df['Marks'].max())
print(df['Marks'].min())
print(df['Marks'].mean())
print(df['Marks'].count())
